### PR TITLE
Add hotfix for auth/refresh error 2000

### PR DESCRIPTION
**Pull request by dvalter**
Hotfix #70 by re-authenticating on refresh error 2000 to make hydroxide usable again

### CODE REVIEW

**Comment by emersion** [comment]
Thanks for the fix! I'd like to try again to fix the refresh route by reverse-engineering the Android app, if that doesn't work I'll merge this workaround.

**Comment by dongcarl** [comment]
Any fix on this?

**Comment by dvalter** [comment]
It's dead now, hydroxide uses an outdated version of API and every request ends up with `[5003] Update required: Please refresh the page to load the latest version of the application`

**Comment by emersion** [comment]
Please rebase against master -- it has https://github.com/emersion/hydroxide/commit/9e57e014ddf7c8e0271dfc420c1d135ab83c60d5 which fixes this issue.

**Comment by dvalter** [comment]
> Please rebase against master -- it has [9e57e01](https://github.com/emersion/hydroxide/commit/9e57e014ddf7c8e0271dfc420c1d135ab83c60d5) which fixes this issue.

Sorry for annoyance, I've messed up with my remotes, so thanks for pointing to the right commit.

**Pull request closed without merging**
