### PR TITLE
Add hostname/port info on options

### PR DESCRIPTION
**Pull request by Thanson16**
Wasn't sure when I downloaded Hydroxide whether I could specify a custom hostname or port. I added a section into the README and put in the info from the `hydroxide help`.

### CODE REVIEW

**Comment by emersion** [comment]
Hmm, I'm not a fan of duplicating information like this. Maybe just add "See `hydroxide help` for commands and options"?

**Comment by Thanson16** [comment]
That is an understandable concern. The issue I was hitting was I didn't know if Hydroxide supported arbitrary hostname/port in the first place, and wasn't wanting to install it if it didn't (I ended up eventually finding a reference to it in an issue).

Would you be okay with a "features" section, with just a bulleted list of what it supports, so the feature is mentioned? I can make a new pull request if you think that solution would be acceptable.

**Comment by PRESFIL** [comment]
@Thanson16 , in some cases not just install, but plus compile that. Or mess around inside foreign sources... :disappointed_relieved:

**Comment by emersion** [comment]
I'm not a fan of this change, sorry.

**Pull request closed without merging**
